import React, { useEffect, useState } from 'react';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar, CartesianGrid } from 'recharts';
import { motion } from 'motion/react';
import { Dataset, AICleaningSuggestion } from '../types';
import { analyzeDatasetWithAI } from '../lib/gemini';
import { applyAction } from '../lib/dataUtils';
import DataTable from './DataTable';
import AIAssistant from './AIAssistant';
import { MessageSquare, LayoutDashboard, Database, Activity, Settings, ChevronRight, CheckCircle2, AlertTriangle, FileUp, Download, Sun, Moon, Sparkles, FileText, Home } from 'lucide-react';
import { cn } from '../lib/utils';

// Helper component for stat cards
function StatCard({ title, value, icon, color }: { title: string; value: string | number; icon: React.ReactNode; color: string }) {
  return (
    <div className="bg-white dark:bg-slate-800 p-4 rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm">
       <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mb-1">{title}</p>
       <div className="flex items-center gap-2">
         {icon && <span className={color}>{icon}</span>}
         <p className={`text-xl font-bold ${color || 'text-slate-900 dark:text-white'}`}>{value}</p>
       </div>
    </div>
  );
}

interface DashboardProps {
  dataset: Dataset;
  onUpdateDataset: (ds: Dataset) => void;
  onUploadNew: () => void;
  onGoHome: () => void;
}

export default function Dashboard({ dataset, onUpdateDataset, onUploadNew, onGoHome }: DashboardProps) {
  const [activeTab, setActiveTab] = useState<'overview' | 'data'>('overview');
  const [suggestions, setSuggestions] = useState<AICleaningSuggestion[]>([]);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isAIPanelOpen, setIsAIPanelOpen] = useState(false);

  useEffect(() => {
    // Only analyze when dataset changes substantially (like initial upload)
    const runAnalysis = async () => {
      setIsAnalyzing(true);
      try {
        const aiSuggestions = await analyzeDatasetWithAI(dataset);
        setSuggestions(aiSuggestions);
      } catch (err) {
        console.error(err);
      } finally {
        setIsAnalyzing(false);
      }
    };
    runAnalysis();
  }, [dataset.id]); 

  const handleApplyAction = (suggestion: AICleaningSuggestion) => {
    // Optimistic UI update or direct processing
    const updated = applyAction(dataset, suggestion.suggestedAction, suggestion.column !== 'global' ? suggestion.column : undefined);
    onUpdateDataset(updated);
    // Remove suggestion
    setSuggestions(prev => prev.filter(s => s.id !== suggestion.id));
  };

  const handleExport = () => {
    // Convert current dataset back to CSV
    const headers = dataset.headers.join(',');
    const rows = dataset.rows.map(row => 
      dataset.headers.map(h => JSON.stringify(row[h] ?? '')).join(',')
    ).join('\n');
    
    const blob = new Blob([headers + '\n' + rows], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cleaned_${dataset.name}`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const handleDownloadReport = () => {
    const reportContent = `CleanFlow AI - Data Cleaning Report
===================================
Dataset: ${dataset.name}
Date: ${new Date().toLocaleString()}

Data Quality Overview
-------------------
Quality Score: ${dataset.stats.qualityScore}/100
Total Rows: ${dataset.stats.rowCount}
Total Columns: ${dataset.stats.colCount}
Missing Values Remaining: ${dataset.stats.missingValues}
Duplicate Rows Remaining: ${dataset.stats.duplicateRows}

Cleaning Activity Log
-------------------
${dataset.history.map((log, i) => `${i + 1}. ${log}`).join('\n')}

---
Generated by CleanFlow AI
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `cleaning_report_${dataset.name}.txt`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  // Mock data for charts
  const typeDistribution = Object.entries(dataset.stats.dataTypes).reduce((acc, [_, type]) => {
    const t = typeof type === 'string' ? type : 'unknown';
    const existing = acc.find(x => x.name === t);
    if (existing) existing.value += 1;
    else acc.push({ name: t, value: 1 });
    return acc;
  }, [] as any[]);

  return (
    <div className="flex h-screen bg-[#f1f5f9] dark:bg-slate-900 font-sans text-slate-800 dark:text-slate-100 overflow-hidden">
      {/* Sidebar */}
      <aside className="w-64 bg-white dark:bg-slate-800 border-r border-slate-200 dark:border-slate-700 flex flex-col hidden md:flex">
        <div 
          className="p-6 flex items-center gap-2 cursor-pointer hover:opacity-80 transition-opacity" 
          onClick={onGoHome}
          title="Return to Home"
        >
          <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
            <Activity className="w-5 h-5 text-white" />
          </div>
          <span className="text-xl font-bold tracking-tight text-slate-900 dark:text-white">CleanFlow AI</span>
        </div>
        <nav className="flex-1 px-4 space-y-1">
          <button 
            onClick={() => setActiveTab('overview')}
            className={cn("w-full flex items-center gap-3 px-3 py-2 rounded-lg font-medium transition-colors text-sm", 
              activeTab === 'overview' ? "bg-slate-100 text-indigo-600 dark:bg-slate-700 dark:text-indigo-400" : "text-slate-500 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-700/50"
            )}
          >
            <LayoutDashboard size={18} /> Dashboard
          </button>
          <button 
            onClick={() => setActiveTab('data')}
            className={cn("w-full flex items-center gap-3 px-3 py-2 rounded-lg font-medium transition-colors text-sm", 
              activeTab === 'data' ? "bg-slate-100 text-indigo-600 dark:bg-slate-700 dark:text-indigo-400" : "text-slate-500 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-700/50"
            )}
          >
            <Database size={18} /> Data Preview
          </button>
          <div className="mt-8 mb-2 px-3 text-xs font-semibold text-slate-400 uppercase tracking-wider">Workspace</div>
          <button 
             onClick={handleDownloadReport}
            className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium text-slate-500 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-700/50 transition-colors"
          >
            <FileText size={18} /> Download Report
          </button>
          <button 
             onClick={onUploadNew}
            className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium text-slate-500 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-700/50 transition-colors"
          >
            <FileUp size={18} /> Upload New
          </button>
          <button 
             onClick={onGoHome}
            className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-sm font-medium text-slate-500 hover:bg-slate-50 dark:text-slate-400 dark:hover:bg-slate-700/50 transition-colors"
          >
            <Home size={18} /> {dataset.id === 'demo-dataset-1' ? 'Exit Demo' : 'Exit to Home'}
          </button>
        </nav>
        <div className="p-4 mt-auto border-t border-slate-100 dark:border-slate-700">
          <div className="p-4 bg-indigo-50 dark:bg-indigo-900/40 rounded-xl">
            <p className="text-xs font-semibold text-indigo-600 dark:text-indigo-400 uppercase mb-1">Current Dataset</p>
            <p className="text-sm font-bold text-slate-900 dark:text-white truncate" title={dataset.name}>{dataset.name}</p>
            <div className="w-full bg-slate-200 dark:bg-slate-700 h-1 rounded-full mt-2">
              <div className="bg-indigo-600 h-1 rounded-full w-[85%]"></div>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col h-full overflow-hidden relative">
        {/* Top Header */}
        <header className="h-16 bg-white dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700 px-6 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <h2 className="text-sm font-semibold text-slate-500 dark:text-slate-400 uppercase tracking-widest hidden sm:block">Active Dataset:</h2>
            <div className="flex items-center gap-2 bg-slate-100 dark:bg-slate-700 px-3 py-1 rounded-full border border-slate-200 dark:border-slate-600">
              <span className="text-sm font-medium text-slate-800 dark:text-slate-200 truncate max-w-[200px]">{dataset.name}</span>
            </div>
            {dataset.id === 'demo-dataset-1' && (
              <span className="bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-300 text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider">Demo Mode</span>
            )}
          </div>
          <div className="flex items-center gap-3">
             <button 
               onClick={onGoHome}
               className="flex items-center gap-1.5 px-3 py-1.5 text-slate-500 hover:text-slate-900 dark:hover:text-white transition-colors bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 rounded-lg text-sm font-medium"
               title={dataset.id === 'demo-dataset-1' ? "Exit Demo" : "Exit to Home"}
             >
               <Home size={16} /> <span className="hidden sm:inline">{dataset.id === 'demo-dataset-1' ? 'Exit Demo' : 'Exit'}</span>
             </button>
             <button 
               onClick={() => {
                 document.documentElement.classList.toggle('dark');
               }}
               className="p-2 text-slate-500 hover:text-slate-900 dark:hover:text-white transition-colors bg-slate-100 dark:bg-slate-700 rounded-full"
             >
               <Moon className="dark:hidden" size={16} />
               <Sun className="hidden dark:block" size={16} />
             </button>
            <div className="hidden sm:flex items-center bg-emerald-50 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 px-3 py-1.5 rounded-full border border-emerald-100 dark:border-emerald-800/50">
              <span className="w-2 h-2 bg-emerald-500 rounded-full mr-2"></span>
              <span className="text-xs font-bold">Data Health: {dataset.stats.qualityScore}%</span>
            </div>
            <button 
              onClick={handleExport}
              className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm font-semibold shadow-sm hover:bg-indigo-700 transition-colors"
            >
              Export Clean Data
            </button>
          </div>
        </header>

        {/* Workspace Grid */}
        <div className="flex-1 overflow-auto p-6 scrollbar-hide">
          {activeTab === 'overview' ? (
            <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 max-w-7xl mx-auto">
              
              {/* Statistics & Data Column */}
              <div className="xl:col-span-8 flex flex-col gap-6">
                 {/* Stats Row */}
                 <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                   <StatCard 
                     title="Total Rows" 
                     value={dataset.stats.rowCount.toLocaleString()} 
                     color="text-slate-900 dark:text-white"
                     icon={null}
                   />
                    <StatCard 
                     title="Columns" 
                     value={dataset.stats.colCount.toLocaleString()} 
                     color="text-slate-900 dark:text-white"
                     icon={null}
                   />
                    <StatCard 
                     title="Missing Values" 
                     value={dataset.stats.missingValues.toLocaleString()} 
                     color={dataset.stats.missingValues > 0 ? "text-amber-600 dark:text-amber-400" : "text-slate-900 dark:text-slate-400"}
                     icon={null}
                   />
                    <StatCard 
                     title="Duplicates" 
                     value={dataset.stats.duplicateRows.toLocaleString()} 
                     color={dataset.stats.duplicateRows > 0 ? "text-indigo-600 dark:text-indigo-400" : "text-slate-900 dark:text-slate-400"}
                     icon={null}
                   />
                 </div>

                 {/* Charts Area */}
                 <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm p-5 flex flex-col">
                   <h3 className="text-xs font-bold uppercase text-slate-400 mb-4">Data Type Distribution</h3>
                   <div className="h-[250px] w-full">
                      <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={typeDistribution} margin={{ top: 0, right: 0, left: 0, bottom: 0 }}>
                          <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#334155" opacity={0.1} />
                          <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                          <YAxis axisLine={false} tickLine={false} tick={{fill: '#64748b', fontSize: 12}} />
                          <Tooltip cursor={{fill: 'rgba(99, 102, 241, 0.05)'}} contentStyle={{ borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }} />
                          <Bar dataKey="value" fill="#4f46e5" radius={[4, 4, 0, 0]} maxBarSize={40} />
                        </BarChart>
                      </ResponsiveContainer>
                   </div>
                 </div>

                 {/* Activity Window */}
                 <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm p-5">
                    <h3 className="text-xs font-bold uppercase text-slate-400 mb-4">Recent Transformations</h3>
                    <div className="space-y-4 max-h-[300px] overflow-y-auto pr-2">
                       {dataset.history.map((log, i) => (
                         <div key={i} className="flex gap-3 text-sm">
                            <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0"></div>
                            <p className="text-slate-600 dark:text-slate-300">{log}</p>
                         </div>
                       )).reverse()}
                    </div>
                 </div>
              </div>

              {/* AI Assistant Column */}
              <div className="xl:col-span-4 flex flex-col gap-6">
                {/* AI Recommendations Panel */}
                <div className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-2xl shadow-sm overflow-hidden flex flex-col max-h-[600px]">
                  <div className="bg-indigo-600 px-4 py-3 flex items-center justify-between shrink-0">
                    <div className="flex items-center gap-2 text-white">
                      <Sparkles className="w-4 h-4" />
                      <span className="text-sm font-bold">AI Recommendations</span>
                    </div>
                    {isAnalyzing ? (
                       <span className="text-white">...</span>
                    ) : (
                       <span className="bg-indigo-400 text-indigo-900 text-[10px] font-bold px-2 py-0.5 rounded-full">
                         {suggestions.length} Pending
                       </span>
                    )}
                  </div>
                  
                  <div className="p-4 space-y-4 flex-1 overflow-y-auto">
                    {isAnalyzing ? (
                      <div className="flex flex-col items-center justify-center py-12 text-slate-500 text-xs">
                        <div className="w-6 h-6 border-2 border-indigo-200 border-t-indigo-600 rounded-full animate-spin mb-3"></div>
                        Generating actions...
                      </div>
                    ) : suggestions.length > 0 ? (
                      suggestions.map((sug) => (
                        <div key={sug.id} className="p-3 bg-slate-50 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-600 rounded-xl relative">
                           <div className="flex items-center justify-between mb-2">
                             <span className="text-[10px] font-bold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-900/30 px-2 py-0.5 rounded uppercase">
                               {sug.column === 'global' ? 'Dataset Wide' : sug.column}
                             </span>
                             <span className="text-[10px] font-bold text-slate-400">{sug.confidenceScore}% Confidence</span>
                           </div>
                           <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed mb-3">
                             <span className="font-bold text-slate-900 dark:text-white block mb-1">{sug.issue}</span>
                             {sug.explanation}
                           </p>
                           <div className="flex gap-2">
                             <button 
                               onClick={() => handleApplyAction(sug)}
                               className="flex-1 py-1.5 bg-indigo-600 hover:bg-indigo-700 text-white text-[10px] uppercase font-bold rounded shadow-sm transition-colors"
                             >
                               Apply Fix
                             </button>
                             <button 
                               onClick={() => setSuggestions(prev => prev.filter(s => s.id !== sug.id))}
                               className="px-3 py-1.5 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700/50 border border-slate-200 dark:border-slate-600 text-slate-600 dark:text-slate-300 text-[10px] uppercase font-bold rounded transition-colors"
                             >
                               Ignore
                             </button>
                           </div>
                        </div>
                      ))
                    ) : (
                      <div className="text-center py-8 text-slate-500">
                        <CheckCircle2 className="mx-auto text-emerald-500 mb-2 w-8 h-8" />
                        <p className="text-sm font-medium">Dataset looks clean!</p>
                      </div>
                    )}
                  </div>
                  
                  {/* Quick Chat Input */}
                  <div className="mt-auto border-t border-slate-100 dark:border-slate-700 p-4 shrink-0 bg-slate-50 dark:bg-slate-800/80">
                     <div className="text-[10px] text-slate-400 font-bold uppercase mb-2">Ask Assistant</div>
                     <div className="relative">
                       <input 
                         type="text" 
                         onClick={() => setIsAIPanelOpen(true)}
                         placeholder="e.g. 'Remove outliers from price'" 
                         className="w-full text-xs bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-lg pl-3 pr-10 py-2.5 focus:ring-2 focus:ring-indigo-500 outline-none shadow-sm cursor-text"
                         readOnly
                       />
                       <button 
                         onClick={() => setIsAIPanelOpen(true)}
                         className="absolute right-2 top-1.5 text-indigo-500 p-1"
                       >
                         <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20"><path d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"/></svg>
                       </button>
                     </div>
                  </div>
                </div>
              </div>

            </div>
          ) : (
            <div className="h-full w-full max-w-7xl mx-auto flex flex-col">
              <DataTable dataset={dataset} />
            </div>
          )}
        </div>
      </main>

      {/* Full AI Chat Overlay */}
      <AIAssistant dataset={dataset} isOpen={isAIPanelOpen} onClose={() => setIsAIPanelOpen(false)} />
    </div>
  );
}
